export default {
  Logo: require('../../assets/images/happycabby.png'),
  icCurLoc: require('../../assets/images/Oval.png'),
  icGreenMarker: require('../../assets/images/greenMarker.png'),
  greenIndicator: require('../../assets/images/greenIndicator.png'),
  cabSuv: require('../../assets/images/top-CheemaX.png'),
  cabComfort: require('../../assets/images/top-Comfort.png'),
  cabStandard: require('../../assets/images/top-CheemaXL.png'),
  carTypeComfort: require('../../assets/images/nearby-car.png'),
  americanExpress: require('../../assets/images/american-express.png'),
  masterCard: require('../../assets/images/mastercard.png'),
  visa: require('../../assets/images/visa.png'),
  profile: require('../../assets/images/blankProfilePic.jpg'),
  car: require('../../assets/images/uberBlack.png'),
};
